name: Linux Development Builds
on: [push]
jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.12"
          pyinstaller_ver: "==6.10.0"
          spec: "vfs_explorer/build/build.spec"
          requirements: "requirements.txt"
          upload_exe_with_name: "vfs_explorer_linux_dev"
      - name: Add to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "vfs_explorer_linux_dev"
