name: Nightly Builds
on: [push]
jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.12"
          pyinstaller_ver: "==5.13.2"
          spec: "vfs_explorer/build/build.spec"
          requirements: "requirements.txt"
          upload_exe_with_name: "VFS Explorer"
          options: --name "VFS Explorer", --contents-directory "vfs_explorer", --noconsole, --add-data=COPYING:License, --clean
